<a href="https://colab.research.google.com/github/peddagoudlasrija-jpg/Movie-recommend-mini-system-/blob/main/Movie_recommended_mini_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
movies = {
    "title": [
        "Avengers: Endgame",
        "Spider-Man: No Way Home",
        "Iron Man",
        "The Dark Knight",
        "Inception",
        "Interstellar",
        "Titanic",
        "The Notebook",
        "Jurassic Park",
        "The Lion King",
        "Frozen",
        "Toy Story",
        "Finding Nemo",
        "Avatar",
        "Black Panther"
    ],

    "genre": [
        "Action Adventure Science Fiction",
        "Action Adventure Science Fiction",
        "Action Science Fiction",
        "Action Crime Drama",
        "Science Fiction Thriller",
        "Science Fiction Drama Adventure",
        "Romance Drama",
        "Romance Drama",
        "Science Fiction Adventure",
        "Animation Adventure Drama",
        "Animation Adventure Fantasy",
        "Animation Comedy Adventure",
        "Animation Adventure Comedy",
        "Science Fiction Adventure",
        "Action Adventure Fantasy"
    ],

    "description": [
        "Superheroes fight to save the world from a powerful enemy",
        "Spider-Man faces villains from different universes",
        "A billionaire creates a powerful armored superhero suit",
        "A superhero fights a dangerous criminal in Gotham City",
        "A thief enters dreams to complete a difficult mission",
        "Astronauts travel through space searching for a new home",
        "A love story between two people on a famous ship",
        "A romantic story about two young people and their love",
        "Scientists discover dinosaurs and struggle to survive",
        "A young lion learns to become the king of the jungle",
        "A princess with magical powers tries to save her kingdom",
        "Toys come alive and experience exciting adventures",
        "A fish searches across the ocean for his lost son",
        "A human explores an alien planet and its civilization",
        "A superhero protects his country using advanced technology"
    ]
}

df = pd.DataFrame(movies)
df

,title,genre,description
0,Avengers: Endgame,Action Adventure Science Fiction,Superheroes fight to save the world from a pow...
1,Spider-Man: No Way Home,Action Adventure Science Fiction,Spider-Man faces villains from different unive...
2,Iron Man,Action Science Fiction,A billionaire creates a powerful armored super...
3,The Dark Knight,Action Crime Drama,A superhero fights a dangerous criminal in Got...
4,Inception,Science Fiction Thriller,A thief enters dreams to complete a difficult ...
5,Interstellar,Science Fiction Drama Adventure,Astronauts travel through space searching for ...
6,Titanic,Romance Drama,A love story between two people on a famous ship
7,The Notebook,Romance Drama,A romantic story about two young people and th...
8,Jurassic Park,Science Fiction Adventure,Scientists discover dinosaurs and struggle to ...
9,The Lion King,Animation Adventure Drama,A young lion learns to become the king of the ...
10,Frozen,Animation Adventure Fantasy,A princess with magical powers tries to save h...
11,Toy Story,Animation Comedy Adventure,Toys come alive and experience exciting advent...
12,Finding Nemo,Animation Adventure Comedy,A fish searches across the ocean for his lost son
13,Avatar,Science Fiction Adventure,A human explores an alien planet and its civil...
14,Black Panther,Action Adventure Fantasy,A superhero protects his country using advance...

In [ ]:
df["features"] = df["genre"] + " " + df["description"]

print("Movie Dataset:")
display(df[["title", "genre", "description"]])

Movie Dataset:

,title,genre,description
0,Avengers: Endgame,Action Adventure Science Fiction,Superheroes fight to save the world from a pow...
1,Spider-Man: No Way Home,Action Adventure Science Fiction,Spider-Man faces villains from different unive...
2,Iron Man,Action Science Fiction,A billionaire creates a powerful armored super...
3,The Dark Knight,Action Crime Drama,A superhero fights a dangerous criminal in Got...
4,Inception,Science Fiction Thriller,A thief enters dreams to complete a difficult ...
5,Interstellar,Science Fiction Drama Adventure,Astronauts travel through space searching for ...
6,Titanic,Romance Drama,A love story between two people on a famous ship
7,The Notebook,Romance Drama,A romantic story about two young people and th...
8,Jurassic Park,Science Fiction Adventure,Scientists discover dinosaurs and struggle to ...
9,The Lion King,Animation Adventure Drama,A young lion learns to become the king of the ...
10,Frozen,Animation Adventure Fantasy,A princess with magical powers tries to save h...
11,Toy Story,Animation Comedy Adventure,Toys come alive and experience exciting advent...
12,Finding Nemo,Animation Adventure Comedy,A fish searches across the ocean for his lost son
13,Avatar,Science Fiction Adventure,A human explores an alien planet and its civil...
14,Black Panther,Action Adventure Fantasy,A superhero protects his country using advance...

In [ ]:
tfidf = TfidfVectorizer(stop_words="english")

tfidf_matrix = tfidf.fit_transform(df["features"])

print("TF-IDF Matrix Shape:", tfidf_matrix.shape)

TF-IDF Matrix Shape: (15, 87)

In [ ]:
similarity = cosine_similarity(tfidf_matrix)

print("Similarity matrix created successfully!")

Similarity matrix created successfully!

In [ ]:
def recommend_movies(movie_name, number_of_movies=5):

    movie_name = movie_name.lower()

    matches = df[df["title"].str.lower() == movie_name]

    if matches.empty:
        print("Movie not found in the dataset.")
        print("\nAvailable movies:")
        for movie in df["title"]:
            print("-", movie)
        return

    index = matches.index[0]

    similarity_scores = list(enumerate(similarity[index]))

    similarity_scores = sorted(
        similarity_scores,
        key=lambda x: x[1],
        reverse=True
    )

    recommendations = []

    for i, score in similarity_scores[1:number_of_movies+1]:
        recommendations.append({
            "Movie": df.iloc[i]["title"],
            "Genre": df.iloc[i]["genre"],
            "Similarity Score": round(score, 3)
        })

    result = pd.DataFrame(recommendations)

    print(f"\nMovies recommended for: {df.iloc[index]['title']}")
    display(result)

In [ ]:
recommend_movies("Avengers: Endgame")

Movies recommended for: Avengers: Endgame

                     Movie                             Genre  Similarity Score
0                 Iron Man            Action Science Fiction             0.271
1  Spider-Man: No Way Home  Action Adventure Science Fiction             0.175
2                   Frozen       Animation Adventure Fantasy             0.137
3            Jurassic Park         Science Fiction Adventure             0.129
4                   Avatar         Science Fiction Adventure             0.129

In [ ]:
recommend_movies("Avengers: Endgame")

Movies recommended for: Avengers: Endgame

                     Movie                             Genre  Similarity Score
0                 Iron Man            Action Science Fiction             0.271
1  Spider-Man: No Way Home  Action Adventure Science Fiction             0.175
2                   Frozen       Animation Adventure Fantasy             0.137
3            Jurassic Park         Science Fiction Adventure             0.129
4                   Avatar         Science Fiction Adventure             0.129

In [ ]:
recommend_movies("Titanic")

Movies recommended for: Titanic

               Movie                             Genre  Similarity Score
0       The Notebook                     Romance Drama             0.646
1      The Lion King         Animation Adventure Drama             0.073
2       Interstellar   Science Fiction Drama Adventure             0.066
3    The Dark Knight                Action Crime Drama             0.065
4  Avengers: Endgame  Action Adventure Science Fiction             0.000

In [ ]:
print("========================================")
print("       MOVIE RECOMMENDATION SYSTEM")
print("========================================")
print("A Python Mini Project")
print("Technology Used: Python, Pandas, Scikit-learn")
print("Recommendation Method: Content-Based Filtering")
print("========================================")

========================================
       MOVIE RECOMMENDATION SYSTEM
========================================
A Python Mini Project
Technology Used: Python, Pandas, Scikit-learn
Recommendation Method: Content-Based Filtering
========================================